config/routes.rb
News::Application.routes.draw do
  resources :posts
  resources :votes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  root 'posts#new'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :body
  validates_presence_of :commentable_id
  validates_presence_of :user_id
  belongs_to :user
  has_many :comments, as: :commentable
  belongs_to :commentable, polymorphic: true

   def post
    if self.commentable_type == "Post"
      self.commentable
    else
      self.commentable.post
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :url, presence: true
  has_many :votes
  belongs_to :user
  has_many :comments, as: :commentable

  def self.sort_by_votes
    all.sort_by { |post| post.calculate_score }.reverse
  end

  def calculate_score
    minutes_since_post = (Time.now - self.created_at.to_time) / 60
    percent_of_day = (200 - minutes_since_post) / 200
    self.votes.count * percent_of_day
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save { self.email = self.email.downcase }
  before_create :create_remember_token
  has_many :posts
  has_many :votes
  has_many :comments

  validates_uniqueness_of :email

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
private 
  
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end        
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = current_user.comments.new
  end

  def create
   @comment = current_user.comments.new(comment_params)

    if @comment.save
     flash[:notice] = "Comment saved"
     redirect_to @comment.commentable
    else 
     flash[:alert] = "Invalid input"
     redirect_to @comment.commentable
    end  
  end

  def show
    @comment = Comment.find(params[:id])
    @newcomment = Comment.new(:commentable_id => @comment.id, :commentable_type => Comment)
  end


private
  def comment_params
    params.require(:comment).permit(:body, :commentable_type, :commentable_id)
  end
end   

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @posts = Post.sort_by_votes
  end
  
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Post saved"
    end  
    redirect_to root_path
  end  

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new(:commentable_id => @post.id, :commentable_type => Post)
  end

private
  def post_params
    params.require(:post).permit(:title, :url)
  end  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
    
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user

      redirect_to root_path
    else
      flash.now[:alert] = "Invalid email/password combination"
      render 'new'
    end    
  end  

  def destroy
    sign_out
    redirect_to root_url 
  end
end  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "#{@user.name} has been saved"
      sign_in @user
      redirect_to root_path
    else
      flash[:notice] = "Please check entries"
      redirect_to 'users_path#new'
    end    
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end    

private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)  
  end
end    

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @post.votes.create(:user_id => current_user.id)
    flash[:notice] = "Vote cast"
    redirect_to root_path
  end
end    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update(remember_token: User.encrypt(remember_token))
    self.current_user = user
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end  
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def signed_in?
    !current_user.nil?
  end
end          

app/views/comments/show.html.erb
<h1>Add Comment</h1>

<%= @comment.user.name %><%= @comment.created_at %>
<br><%= @comment.body %>

<br>
<%= form_for @newcomment do |f| %>
  <%= f.hidden_field :commentable_id %>
  <%= f.hidden_field :commentable_type %>
  <%= f.label :reply %>
  <%= f.text_field :body %>
  <%= f.submit "Submit" %>
<% end %>

<%= link_to "Original Post", @comment.post %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav nav-tabs">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in?%>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
            <li><%= link_to current_user.name, current_user %></li>
            <li>
              <%= link_to "Sign out", signout_path, method: "delete" %>
            </li>
          
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Sign up", signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>News</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>  
</div> 
    
<div class="content">
  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <%= yield %>
 
</div>
</body>
</html>

app/views/posts/new.html.erb
<% if signed_in? %>
  <h1>Create new entry</h1>
  <div >
    <%= form_for @post do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :url %>
      <%= f.text_field :url %>
      <%= f.submit "Post", :class => 'btn btn-success' %>
    <% end %>
  </div> 
<% end %>     

<ul>
<% @posts.each do |post| %>
  <li><%= link_to "#{post.title}", "http://#{post.url}", :target => "_blank" %>
      <div class = "post-elements"><%=  "Votes:  #{post.votes.count} Posted by: #{post.user.name}"%></div>
      <span class = "post-elements"><%=  "Created:  #{post.created_at.pretty_inspect[0..21]}"%></span>
      <span class = "post-elements"><%=  link_to "Comments:  #{post.comments.count}", post %></span>

      <% if post.votes.find_by(:user_id => current_user) == nil && signed_in? %>
        <%= button_to "Vote up", { :controller => :votes,
                                 :action => "show",
                                 :id => post.id },
                                 :method => :get %>
      <% end %>                           
  </li>
<% end %>
</ul>  

app/views/posts/show.html.erb
<h2><%= link_to "#{@post.title }", "http://#{@post.url}", :target => "_blank" %></h2>
 

<%= form_for @comment do |f| %>
  <%= f.hidden_field :commentable_id %>
  <%= f.hidden_field :commentable_type %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit "Submit" %>
<% end %>

<ul>
  <% @post.comments.each do |comment| %>

    <li><%= link_to "#{comment.body}", comment %>
        <span class = "post-elements"><%= comment.user.name %></span>
        <ul><% comment.comments.each do |comment| %>
               <li><%= link_to "#{comment.body}", comment %></li>
            <% end %> </ul>   

    </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <li><%= user.name %></li>
<% end %>  

app/views/users/new.html.erb
<h1>User sign-up</h1>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  <%= f.submit "Register" %>
<% end %>  

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% @user.posts.each do |post| %>
  <li><%= post.title %></li>
<% end %>  